# Generated by Django 4.1.3 on 2022-11-11 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(blank=True, null=True)),
                ('x_axis_title', models.CharField(max_length=50)),
                ('y_axis_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Graphs.graph', verbose_name='IdGraph')),
            ],
        ),
        migrations.CreateModel(
            name='y_axis_labels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Graphs.graph', verbose_name='IdGraph')),
            ],
        ),
        migrations.CreateModel(
            name='x_axis_labels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Graphs.graph', verbose_name='IdGraph')),
            ],
        ),
        migrations.CreateModel(
            name='entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Entity', models.CharField(max_length=50)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Graphs.graph', verbose_name='IdGraph')),
                ('year', models.ManyToManyField(to='Graphs.year')),
            ],
        ),
        migrations.CreateModel(
            name='census',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DecimalField(decimal_places=1, max_digits=2)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Graphs.entity', verbose_name='IdEntity')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Graphs.graph', verbose_name='IdGraph')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Graphs.year', verbose_name='IdYear')),
            ],
        ),
    ]
