# Generated by Django 4.1.3 on 2022-11-11 03:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('x_axis_title', models.CharField(max_length=50)),
                ('y_axis_title', models.CharField(max_length=50)),
                ('x_axis_values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=1)),
                ('y_axis_values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=1)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('censusdata', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=1)),
            ],
        ),
    ]
