# Generated by Django 4.1.3 on 2022-11-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinamicgraphs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='x_axis_range',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='y_axis_range',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='year_range',
        ),
        migrations.AddField(
            model_name='graph',
            name='x_axis_range_end',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='graph',
            name='x_axis_range_start',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='graph',
            name='y_axis_range_end',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='graph',
            name='y_axis_range_start',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='graph',
            name='year_range_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='year_range_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='census',
            name='census',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
