# Generated by Django 4.1.3 on 2022-11-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinamicgraphs', '0002_remove_graph_x_axis_range_remove_graph_y_axis_range_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='censuspoblation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('state_title', models.CharField(max_length=50)),
                ('gender_title', models.CharField(max_length=50)),
                ('census', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='census',
        ),
    ]
